// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFeKr5Uyuj5UMM9TIqdd1CLoxZ50uxxc',
    appId: '1:970464036115:web:f93f73647acc17dd3546e6',
    messagingSenderId: '970464036115',
    projectId: 'predstroke-sca',
    authDomain: 'predstroke-sca.firebaseapp.com',
    storageBucket: 'predstroke-sca.firebasestorage.app',
    measurementId: 'G-ZZE2JXXWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuOaU24ziA5836HHRYomQhMZ14_3ODsEg',
    appId: '1:970464036115:android:5b2cf1aa7aa54d343546e6',
    messagingSenderId: '970464036115',
    projectId: 'predstroke-sca',
    storageBucket: 'predstroke-sca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Tt_UTxfjPRjDAO5JVh6RIQonl2SpRkU',
    appId: '1:970464036115:ios:212c447dfe8a330b3546e6',
    messagingSenderId: '970464036115',
    projectId: 'predstroke-sca',
    storageBucket: 'predstroke-sca.firebasestorage.app',
    iosClientId: '970464036115-8il9ma8t0t0chu29o2shg585v8la609m.apps.googleusercontent.com',
    iosBundleId: 'com.example.predstroke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Tt_UTxfjPRjDAO5JVh6RIQonl2SpRkU',
    appId: '1:970464036115:ios:212c447dfe8a330b3546e6',
    messagingSenderId: '970464036115',
    projectId: 'predstroke-sca',
    storageBucket: 'predstroke-sca.firebasestorage.app',
    iosClientId: '970464036115-8il9ma8t0t0chu29o2shg585v8la609m.apps.googleusercontent.com',
    iosBundleId: 'com.example.predstroke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFeKr5Uyuj5UMM9TIqdd1CLoxZ50uxxc',
    appId: '1:970464036115:web:41b9c7bda5ffaf9c3546e6',
    messagingSenderId: '970464036115',
    projectId: 'predstroke-sca',
    authDomain: 'predstroke-sca.firebaseapp.com',
    storageBucket: 'predstroke-sca.firebasestorage.app',
    measurementId: 'G-Q6HCNG0P0G',
  );
}
